/*  lkmTest05.c - The simplest kernel module.

* Copyright (C) 2013-2022 Xilinx, Inc
* Copyright (c) 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR("Xilinx Inc.");
MODULE_DESCRIPTION("lkmTest05 - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "lkmTest05"

//TODO: Delete if not needed
/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
unsigned myint = 0xdeadbeef;
char *mystr = "default";
module_param(myint, int, S_IRUGO);
module_param(mystr, charp, S_IRUGO);



//TODO: Fill with the correct register map
#pragma pack(1)
struct testPeriph_reg {
};
#pragma pack()





/* Driver private data */
struct lkmTest05_local {
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	unsigned long mem_size;
	void __iomem *base_addr;
    struct testPeriph_reg *reg;
	spinlock_t lock;
};



static irqreturn_t lkmTest05_irq(int irq, void *lp)
{
	struct lkmTest05_local *_lp = (struct lkmTest05_local*) lp;
    struct testPeriph_reg *reg = _lp->reg;

	printk("lkmTest05 interrupt\n");

	//TODO: Insert here the code to handle the interrupt

	return IRQ_HANDLED;
}



static int lkmTest05_probe(struct platform_device *pdev)
{
	int r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
    struct resource *region;
	struct device *dev = &pdev->dev;
	struct lkmTest05_local *lp = NULL;

	int rc = 0;
	dev_info(dev, "Device Tree Probing START\n");


	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "Invalid address\n");
		return -ENODEV;
	}

	// Allocate the device in memory
	lp = (struct lkmTest05_local *) devm_kzalloc(dev, sizeof(struct lkmTest05_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate lkmTest05 device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);

	spin_lock_init(&lp->lock);

	// Save mem parameteress in local driver structure
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;
	lp->mem_size = resource_size(r_mem);


	//TODO: Delete it. Just for debug
	dev_err(dev, "****************** DEGUG ****************** Lp Size: 0x%08x\n", lp->mem_size);



	region = devm_request_mem_region(dev,
									 lp->mem_start,
									 lp->mem_size,
									 dev_name(dev));
    if (region == NULL) {
		dev_err(dev, "Couldn't lock memory region at %p\n", (void *)lp->mem_start);
        return -EBUSY;
    }



	// Note: Non cached by default
	lp->base_addr = devm_ioremap(dev, lp->mem_start, lp->mem_size);
    if(lp->base_addr <= 0) {
		dev_err(dev, "Could not allocate iomem.\n");
        return -EIO;
    }

	lp->reg = lp->base_addr;

	

	/* Get device's irq number(s) */
    lp->irq = platform_get_irq(pdev, 0);
    if(lp->irq < 0) {
		dev_info(dev, "No IRQ found\n");
		goto okNoIntr;
    }
    
	rc = devm_request_irq(dev, lp->irq, lkmTest05_irq, (IRQF_TRIGGER_RISING | IRQF_SHARED), DRIVER_NAME, lp);
    if(rc < 0) {
		dev_err(dev, "Could not allocate interrupt %d.\n", lp->irq);
        return rc;
    }
	

ok: 
	dev_info(dev,"lkmTest05 at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
	return 0;

okNoIntr: 
	dev_info(dev,"lkmTest05 at 0x%08x mapped to 0x%08x\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr);
	return 0;

}






static int lkmTest05_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct lkmTest05_local *lp = dev_get_drvdata(dev);
	
	//TODO: Unregister the character device here
	
	return 0;
}









#ifdef CONFIG_OF
static struct of_device_id lkmTest05_of_match[] = {
	{ .compatible = "xlnx,test-peripherals-2.0", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, lkmTest05_of_match);
#else
# define lkmTest05_of_match
#endif

static struct platform_driver lkmTest05_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= lkmTest05_of_match,
	},
	.probe		= lkmTest05_probe,
	.remove		= lkmTest05_remove,
};

static int __init lkmTest05_init(void)
{
	printk(KERN_INFO "LKM Test05 Inserted.\n");
	printk(KERN_INFO "Module parameters were (0x%08x) and \"%s\"\n", myint, mystr);

	return platform_driver_register(&lkmTest05_driver);
}

static void __exit lkmTest05_exit(void)
{
	platform_driver_unregister(&lkmTest05_driver);
	printk(KERN_ALERT "Goodbye module world.\n");
}


module_init(lkmTest05_init);
module_exit(lkmTest05_exit);
